<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'first_name' => 'Marie',
                'last_name' => 'Dubois',
                'email' => 'marie.dubois@email.com',
                'phone' => '06 12 34 56 78',
                'date_of_birth' => '1995-03-15',
                'gender' => 'female',
                'student_id' => 'INF001',
                'program' => 'Infographie & Design Graphique',
                'level' => 'Avancé',
                'specialization' => 'Photoshop & Illustrator',
                'address' => '123 Rue de la Paix',
                'city' => 'Paris',
                'country' => 'France',
                'profile_photo' => null,
                'status' => 'active',
                'gpa' => 16.5,
                'credits_earned' => 85,
            ],
            [
                'first_name' => 'Pierre',
                'last_name' => 'Martin',
                'email' => 'pierre.martin@email.com',
                'phone' => '06 23 45 67 89',
                'date_of_birth' => '1992-07-22',
                'gender' => 'male',
                'student_id' => 'INF002',
                'program' => 'Infographie & Design Graphique',
                'level' => 'Intermédiaire',
                'specialization' => 'InDesign & Mise en page',
                'address' => '456 Avenue des Champs',
                'city' => 'Lyon',
                'country' => 'France',
                'profile_photo' => null,
                'status' => 'active',
                'gpa' => 14.2,
                'credits_earned' => 72,
            ],
            [
                'first_name' => 'Sophie',
                'last_name' => 'Leroy',
                'email' => 'sophie.leroy@email.com',
                'phone' => '06 34 56 78 90',
                'date_of_birth' => '1997-11-08',
                'gender' => 'female',
                'student_id' => 'INF003',
                'program' => 'Infographie & Design Graphique',
                'level' => 'Débutant',
                'specialization' => 'Photoshop Fondamentaux',
                'address' => '789 Boulevard Saint-Michel',
                'city' => 'Marseille',
                'country' => 'France',
                'profile_photo' => null,
                'status' => 'active',
                'gpa' => 13.8,
                'credits_earned' => 45,
            ],
            [
                'first_name' => 'Thomas',
                'last_name' => 'Rousseau',
                'email' => 'thomas.rousseau@email.com',
                'phone' => '06 45 67 89 01',
                'date_of_birth' => '1994-01-30',
                'gender' => 'male',
                'student_id' => 'INF004',
                'program' => 'Strategy Business & Design',
                'level' => 'Avancé',
                'specialization' => 'Stratégie Digitale',
                'address' => '321 Rue de Rivoli',
                'city' => 'Toulouse',
                'country' => 'France',
                'profile_photo' => null,
                'status' => 'graduated',
                'gpa' => 17.9,
                'credits_earned' => 120,
            ],
            [
                'first_name' => 'Emma',
                'last_name' => 'Moreau',
                'email' => 'emma.moreau@email.com',
                'phone' => '06 56 78 90 12',
                'date_of_birth' => '1996-09-12',
                'gender' => 'female',
                'student_id' => 'INF005',
                'program' => 'Infographie & Design Graphique',
                'level' => 'Intermédiaire',
                'specialization' => 'Illustrator Vectoriel',
                'address' => '654 Place Bellecour',
                'city' => 'Nice',
                'country' => 'France',
                'profile_photo' => null,
                'status' => 'active',
                'gpa' => 15.3,
                'credits_earned' => 68,
            ],
            [
                'first_name' => 'Lucas',
                'last_name' => 'Bernard',
                'email' => 'lucas.bernard@email.com',
                'phone' => '06 67 89 01 23',
                'date_of_birth' => '1993-05-18',
                'gender' => 'male',
                'student_id' => 'INF006',
                'program' => 'Strategy Business & Design',
                'level' => 'Avancé',
                'specialization' => 'Marketing Visuel',
                'address' => '987 Cours Mirabeau',
                'city' => 'Bordeaux',
                'country' => 'France',
                'profile_photo' => null,
                'status' => 'suspended',
                'gpa' => 12.1,
                'credits_earned' => 35,
            ],
            [
                'first_name' => 'Camille',
                'last_name' => 'Petit',
                'email' => 'camille.petit@email.com',
                'phone' => '06 78 90 12 34',
                'date_of_birth' => '1998-12-03',
                'gender' => 'female',
                'student_id' => 'INF007',
                'program' => 'Infographie & Design Graphique',
                'level' => 'Débutant',
                'specialization' => 'InDesign & Print',
                'address' => '147 Rue du Faubourg',
                'city' => 'Lille',
                'country' => 'France',
                'profile_photo' => null,
                'status' => 'active',
                'gpa' => 14.7,
                'credits_earned' => 28,
            ],
            [
                'first_name' => 'Antoine',
                'last_name' => 'Durand',
                'email' => 'antoine.durand@email.com',
                'phone' => '06 89 01 23 45',
                'date_of_birth' => '1991-08-25',
                'gender' => 'male',
                'student_id' => 'INF008',
                'program' => 'Strategy Business & Design',
                'level' => 'Expert',
                'specialization' => 'Brand Strategy',
                'address' => '258 Avenue de la République',
                'city' => 'Nantes',
                'country' => 'France',
                'profile_photo' => null,
                'status' => 'graduated',
                'gpa' => 18.2,
                'credits_earned' => 120,
            ],
        ];

        foreach ($students as $studentData) {
            Student::create($studentData);
        }
    }
}
